<?php

namespace App\Services\Commission;

use App\Models\Commission;
use App\Models\Order;
use Illuminate\Support\Collection;

interface CommissionCalculatorInterface
{
    /**
     * Calculate and persist all commissions generated by $order.
     *
     * @return Collection<int, Commission>
     */
    public function calculate(Order $order): Collection;
}
