<?php

namespace App\Services\Commission;

use App\Models\Commission;
use App\Models\Order;
use Illuminate\Support\Collection;

interface CommissionCalculatorInterface
{
    /**
     * The `active_plan_type` value this calculator handles, e.g. "unilevel".
     * Used by CommissionCalculatorRegistry to resolve the right calculator
     * without CommissionService needing to know every plan type that exists.
     */
    public function planType(): string;

    /**
     * Calculate and persist all commissions generated by $order.
     *
     * @return Collection<int, Commission>
     */
    public function calculate(Order $order): Collection;
}
